version: "3.7"
services:
  github_test:
    tty: true
    build:
      context: .
    ports:
      - 3001:3000
    volumes:
      - .:/usr/src/app:delegated
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock
      - notused:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  notused:
