name: Greet Everyone

on: [push]
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

  my_second_job:
    name: My second job
    needs: my_first_job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
