name: Test github workflows
on: [push]
jobs:
  install-and-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, Test, Prettier check and Eslint check.
        run: |
          yarn
          yarn test:watch
          yarn prettier:check
          yarn lint:check
        env:
          CI: true

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: install-and-check
    steps:
      - uses: actions/checkout@master

      - name: Use Docker node alpine
        uses: docker://node:alpine

      - name: Docker build image
        run: |
          docker image build -t ${{ secrets.DOCKER_REPO }}:develop -t ${{ secrets.DOCKER_REPO }}:develop --file Dockerfile .
