name: Test github workflows
on: [push, pull_request]
jobs:
  install-and-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn

      - name: Test, Prettier check and Eslint check.
        if: success()
        run: |
          yarn test:watch
          yarn prettier:check
          yarn lint:check
        env:
          CI: true

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: install-and-check
    steps:
      - uses: actions/checkout@master

      - name: Publish to Registry
        if: success() && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop') 
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          tag_names: true
          snapshot: true
