name: Greet Everyone

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install
        uses: actions/checkout@v1
        uses: actions/setup-node@v1
          run: yarn
    
      - name: Check
        uses: actions/checkout@v1
        uses: actions/setup-node@v1
          run: yarn test

      - name: Build
        uses: actions/checkout@v1
        uses: actions/setup-node@v1
          run: yarn build
