name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  install-and-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, Test, Prettier check and Eslint check.
        run: |
          yarn
          yarn test:watch
          yarn prettier:check
          yarn lint:check
        env:
          CI: true

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: install-and-check
    steps:
      - uses: actions/checkout@master
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_REPO}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry
        run: echo ${{ secrets.DOCKER_REPO }} ${{ secrets.DOCKER_USERNAME }}
