name: Greet Everyone

on: [push]
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - run: echo This event is runing my_first_job.

  my_second_job:
    name: My second job
    needs: my_first_job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: |
          yarn  
          yarn test:watch
